### ISSUE TITLE
invalid record

### ISSUE THREAD

**Issue by ofirdev** [kakwa/libemf2svg#14]
I can open this [WMF](https://bugs.documentfoundation.org/attachment.cgi?id=75285) with MS Paint but libemf2svg gives me a warning:
WARNING(scanning): EMF file does not begin with an EMR_HEADER record
ABORTING(scanning): invalid record - corrupted file?

WMF was taken from [here](https://bugs.documentfoundation.org/show_bug.cgi?id=47243).

**Comment by ofirdev** [comment]
Another [WMF](https://bugs.documentfoundation.org/attachment.cgi?id=126980) with the same problem.
Taken from [here](https://bugs.documentfoundation.org/show_bug.cgi?id=39894).

**Comment by kakwa** [comment]
libemf2svg doesn't handle WMF files.

You can use http://wvware.sourceforge.net/libwmf.html for that (I use it in https://github.com/kakwa/libvisio2svg)
