### ISSUE TITLE
Missing David glyphs

### ISSUE THREAD

**Issue by ofirdev** [kakwa/libemf2svg#17]
There are four David glyphs that are not presented:
```
<GlyphID id="205" name="finalkafwithsheva"/>
<GlyphID id="206" name="finalkafwithqamats"/>
<GlyphID id="207" name="lamedwithholam"/>
<GlyphID id="208" name="lamedwithdageshandholam"/>
```

They can be replaced with a combination of existing Unicode characters:
For example: finalfakwithsheva can be replaced with: U+05DA and U+05B0 

The text in the following files is missing:
Example1: (David and Arial):
https://drive.google.com/open?id=0B0odzw1WMqkGYy12SWZuVVNBbW8

Example2 (David):
https://drive.google.com/open?id=0B0odzw1WMqkGRHZGWThEd0ozV3c

**Comment by ofirdev** [comment]
Better example:
https://drive.google.com/open?id=0B0odzw1WMqkGRWhPTjFTZ1dvSVE

**Comment by kakwa** [comment]
As the reverse mapping are not defined statically anymore, I think this issue can be closed. The proper David font file must be installed on the system doing the conversion.
