### ISSUE TITLE
Inclusion of reverse CMAP table is legally problematic 

### ISSUE THREAD

**Issue by StefanBruens** [kakwa/libemf2svg#18]
The CMAP tables are, as part of the copyrighted fonts, also copyrighted, and are clearly not GPL-2.0.

- libemf2svg should not distribute font_mapping.c
- libemf2svg should add a possibility to add a glyph->unicode reverse mapping at runtime

**Comment by ofirdev** [comment]
Is it possible to use something similar to this?
https://bugs.freedesktop.org/attachment.cgi?id=125144&action=edit

**Comment by kakwa** [comment]
It was a bit more complicated than that :) (most of the work is in this commit: https://github.com/kakwa/libemf2svg/commit/1c989828ba62e5cab09f1758821bd1b8ebf08eae)

The reverse cmap decoding is done dynamically now.

Now libemf2svg uses libfontconfig (to try to find the corresponding .ttf file from the font family, weight and italic) and libfreetype for parsing the cmap table using UNICODE.

The static reverse mapping tables are completely removed (including from the git history).

The drawbacks are that the corresponding fonts must be installed on the system doing the conversion and libemf2svg has 2 new dependencies (libfontconfig, libfreetype).
