### ISSUE TITLE
Homebrew formula

### ISSUE THREAD

**Issue by tekwiz** [kakwa/libemf2svg#19]
I would like to create and [Homebrew](https://brew.sh) formula for libemf2svg and submit it to [homebrew-core](https://github.com/Homebrew/homebrew-core).  The build on macOS Sierra was very straight-forward with the dependencies already in Homebrew, so the formula should be very simple.  Before I do this though, I want to make sure you, @kakwa, are OK with me submitting a formula for your project.  Also, I have two questions:

1. Are there any known restrictions on dependency versions, OS X versions, or architectures?
2. Would it be acceptable to create and distribute ["bottles"](https://docs.brew.sh/Bottles.html), i.e. binary packages, given your license and the project's dependency licenses?  If you're unsure, I'm happy to dig into it.

**Comment by kakwa** [comment]
There is no issues in packaging it for OS X.

As I was requested a few times to support OS X, I've added an OS X environment in travis-ci for that use case.

1) I don't know any limitation on version (I would a little be cautious on libpng however), also, you need to use libvisio2svg >= 0.5.0 with libemf2svg >= 1.0.0 (API break at that version).
For the architecture, as long as it's a little endian architecture, it should work correctly. There are issues on Big Endian architecture like SPARC but I don't think that's an issue for OSX ^^.

2) No issue here, this project is licensed under GPLv2 like many other projects already distributed for OS X, it's derived partly from Inkscape code (the EMF parser part).

Also, I may have to add libfreetype as a dependency in future version to solve https://github.com/kakwa/libemf2svg/issues/18 (inclusion of reverse cmap table for font decoding) cleanly. Related to this ticket, I would advice you to not package the master branch directly but the last tag (1.0.1) which doesn't include these reverse mappings.
