### ISSUE TITLE
Error when building

### ISSUE THREAD

**Issue by grf692** [kakwa/libemf2svg#20]
Hello,

I am trying to build the lib on my fresh Centos install but I am stuck - please see attached file.
May you please assist ?

Thanks a lot and best regards,
Gaetan

[lib-make.txt](https://github.com/kakwa/libemf2svg/files/1217497/lib-make.txt)

**Comment by pea-arthur** [comment]
Sorry, to hijack your thread. 
I'm also having an error compiling on  3.16.0-30-generic #40~14.04.1-Ubuntu
[libemf2svg_compile_error.txt](https://github.com/kakwa/libemf2svg/files/1234039/libemf2svg_compile_error.txt)

**Comment by pea-arthur** [comment]
I was able to build successfully on:
Linux galliumos 4.8.17-galliumos #1 SMP PREEMPT galliumos4 Thu Feb 23 02:27:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by kakwa** [comment]
@gatsss the issue is fixed.

Looked like https://sourceware.org/bugzilla/show_bug.cgi?id=16907

(#define in argp.h missing with other headers).
