### ISSUE TITLE
Arrows not converted

### ISSUE THREAD

**Issue by dxdc** [kakwa/libemf2svg#21]
This is a great library and will be incredibly useful to handle this MS Word image format (especially on Mac). I tried it for this case, and it seems it doesn't know how to convert arrows. Sharing the original EML file so you can use it for future development.

![image](https://user-images.githubusercontent.com/7200365/30813559-5dd50316-a1d3-11e7-85c4-5c16f53881e7.png)

[image2.emf.zip](https://github.com/kakwa/libemf2svg/files/1329794/image2.emf.zip)

**Comment by kakwa** [comment]
Hello, there was various issues at play here, but they should be fixed now.

See commit: https://github.com/kakwa/libemf2svg/commit/50652868a0a4df55843cb6d2e9e352d91a9cf0a8 for more details

**Comment by dxdc** [comment]
@kakwa thanks!
