### ISSUE TITLE
yum install error 

### ISSUE THREAD

**Issue by qqxhb** [kakwa/libemf2svg#27]
No package libpng-dev libc6-dev libfontconfig1-dev libfreetype6-dev

**Comment by kakwa** [comment]
As specified in the README, this is valid for Debian.

For CentOS/RHEL/Fedora (or other distros like arch or gentoo), the packages names are different and need to be searched.

Here is a list a necessary packages but I'm not sure it's exhaustive:

`yum install cmake libpng-devel clang freetype-devel fontconfig-devel`
