### ISSUE TITLE
Debian dependencies

### ISSUE THREAD

**Issue by merkys** [kakwa/libemf2svg#35]
Building on Debian unstable, the following dependencies are required on top of the base system (apart from what is already in README.md):

* libpng-dev
* pkg-config
* zlib1g-dev

Could you please add them to README.md too?

**Comment by kakwa** [comment]
libpng-dev was already present, I've added the other twos.

I'm a bit puzzled by zlib1g-dev however, it's a dependency of libpng-dev and is not required here, or am I missing something?

**Comment by merkys** [comment]
> libpng-dev was already present, I've added the other twos.

Indeed, libpng-dev was present. My overlook, sorry.

> I'm a bit puzzled by zlib1g-dev however, it's a dependency of libpng-dev and is not required here, or am I missing something?

True, zlib1g-dev is pulled in by libpng-dev, again my overlook. Must be because cmake checks for ZLIB and then for PNG library headers. So from my initial list only pkg-config was missing in README.md. Thank you for adding it.
